#!/bin/bash
# Apple iCloud/App-Specific Password Setup for @tempo
echo "================================================================"
echo "APPLE ICLOUD/AIRPORT PASSWORD SETUP"
echo "================================================================"
echo ""
echo "NOTE: Apple uses App-Specific Passwords for security"
echo "You CANNOT use your main Apple ID password"
echo ""
echo "STEP 1: Generate App-Specific Password"
echo "---------------------------------------"
echo "1. Go to: https://appleid.apple.com/"
echo "2. Sign in with your Apple ID"
echo "3. Go to 'Sign-In and Security' > 'App-Specific Passwords'"
echo "4. Click 'Generate an app-specific password'"
echo "5. Label: 'Tempo Calendar Integration'"
echo "6. Copy the generated password (it looks like: xxxx-xxxx-xxxx-xxxx)"
echo ""
echo "STEP 2: Store Password Securely"
echo "-------------------------------"
echo "Run this command (replace YOUR_PASSWORD):"
echo ""
echo "  echo 'APPLE_PASSWORD=YOUR_PASSWORD' | hermes -p tempo auth apple"
echo ""
echo "Or store manually in:"
echo "  ~/.hermes/profiles/tempo/credentials/apple-app-password.enc"
echo ""
echo "STEP 3: iCloud Calendar Access"
echo "-------------------------------"
echo "To access iCloud Calendars:"
echo ""
echo "Option A: CalDAV (Recommended)"
echo "  Server: https://caldav.icloud.com/"
echo "  Username: Your iCloud email"
echo "  Password: App-specific password (from Step 1)"
echo ""
echo "Option B: Apple Developer API (Advanced)"
echo "  Requires Apple Developer account ($99/year)"
echo "  Uses EventKit API via native app"
echo "  Not recommended for this use case"
echo ""
echo "STEP 4: Enable Calendar Access"
echo "-----------------------------"
echo "1. On your iPhone/Mac: Settings > [Your Name] > iCloud"
echo "2. Ensure 'Calendars' is enabled"
echo "3. On Mac: Calendar app > Preferences > Accounts"
echo "4. Ensure iCloud Calendars are checked"
echo "================================================================"
echo ""
echo "SECURITY NOTES:"
echo "  • App-specific password: Limited scope, can be revoked"
echo "  • Main Apple ID password: NEVER shared"
echo "  • Revoke access: appleid.apple.com anytime"
echo "  • Credentials stored with 600 permissions (owner only)"
