#!/bin/bash
# Google Calendar OAuth Setup Script for @tempo
# This script guides you through creating Google OAuth credentials

echo "================================================================"
echo "GOOGLE CALENDAR API AUTHORIZATION SETUP"
echo "================================================================"
echo ""
echo "This will set up OAuth2 credentials for Google Calendar access."
echo ""
echo "STEP 1: Create Google Cloud Project"
echo "-------------------------------------"
echo "1. Go to: https://console.cloud.google.com/"
echo "2. Create a new project (or use existing)"
echo "   - Project name: Tempo Calendar Integration"
echo ""
echo "STEP 2: Enable Google Calendar API"
echo "----------------------------------"
echo "1. In Google Cloud Console, go to 'APIs & Services' > 'Library'"
echo "2. Search for 'Google Calendar API'"
echo "3. Click 'Enable'"
echo ""
echo "STEP 3: Configure OAuth Consent Screen"
echo "--------------------------------------"
echo "1. Go to 'APIs & Services' > 'OAuth consent screen'"
echo "2. Select 'External' (unless you're in a Google Workspace)"
echo "3. Fill in:")
echo "   - App name: Tempo Personal Calendar"
echo "   - User support email: {your-email}"
echo "   - Developer contact: {your-email}"
echo "4. Add scopes:")
echo "   - .../auth/calendar (See, edit, share your calendars)"
echo "   - .../auth/calendar.events (View and manage events)"
echo ""
echo "STEP 4: Create OAuth Credentials"
echo "--------------------------------"
echo "1. Go to 'APIs & Services' > 'Credentials'"
echo "2. Click 'Create Credentials' > 'OAuth client ID'"
echo "3. Application type: 'Desktop app'"
echo "4. Name: 'Tempo Desktop Client'"
echo "5. Click 'Create'"
echo ""
echo "STEP 5: Download Credentials"
echo "------------------------------"
echo "1. Click the download icon (⬇️) next to your new OAuth client"
echo "2. Save the JSON file (e.g., 'client_secret_xxx.json')"
echo ""
echo "STEP 6: Store Credentials Securely"
echo "----------------------------------"
echo "Run: hermes -p tempo auth google /path/to/client_secret_xxx.json"
echo ""
echo "This will:"
echo "  - Securely store the credentials"
echo "  - Open browser for OAuth authorization"
echo "  - Store refresh token for ongoing access"
echo "================================================================"
